### ISSUE TITLE
XEO.Clip Example

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeogl#113]
Is XEO.Clip and XEO.Clips known to be working properly in xeoEngine? I can't find any example which I can get to work. I'm trying to create an elevation cross-section (which I can probably fake if I need to).

**Comment by xeolabs** [comment]
No they're completely inactive at the moment (generating no shader code yet). I'll bump them up a priority.

**Comment by philmaker1** [comment]
I'm just making a simple code exercise for my portfolio to demo locating services using sensors. I'm planning to use the scroll wheel to change the elevation cross-section to be able to peer into a building floor for example. If I just use voxel visibility for now that will probably be OK. If I do take it upon my self to do mesh subtraction I hope this will be fast enough for the wheel interaction.

**Comment by xeolabs** [comment]
Clipping's working now: 
http://xeogl.org/examples/#clipping_userClipPlanes
