### ISSUE TITLE
Scene Input Conflicts with Multiple Scenes

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeogl#117]
I have two scenes in my webpage. The first scene has mouseover and mousedown input handlers registered. The second scene has no input handing registered. The issue is that mouse events of the second scene are being delivered to the handlers of the first scene.

xeoEngine v0.1.0 Built on 2016-10-04
Master, Chrome, Chromebook/Linux

Please let me know if this is not a known or easily discoverable issue and I'll submit an example.

**Comment by philmaker1** [comment]
These lines in xeogl.Input might be incorrect but not sure yet if they are causing the problem I'm seeing.
https://github.com/xeolabs/xeogl/blob/master/src/input/input.js#L221
https://github.com/xeolabs/xeogl/blob/master/src/input/input.js#L241

**Comment by philmaker1** [comment]
Also, locally, I changed the following two lines to: cfg.element.addEventListener instead of document.addEventListener
https://github.com/xeolabs/xeogl/blob/master/src/input/input.js#L261
https://github.com/xeolabs/xeogl/blob/master/src/input/input.js#L383
But I don't fully understand if this is going to break something else or not.

**Comment by xeolabs** [comment]
I just observed this issue in [this example](http://xeogl.org/examples/scene_multipleScenes.html), with the help of [this gist](https://gist.github.com/xeolabs/1e348a408cd25e35e1960d5d6cac26c8) which I dropped in the console to log pick events. Will fix in a couple of days.

**Comment by xeolabs** [comment]
Applied your fix @philmaker1
