### ISSUE TITLE
scene.destroy() generates an error

### ISSUE THREAD

**Issue by bastienmenis** [xeolabs/xeogl#126]
Calling `scene.destroy()` generates an error. I am using the build included in bimSurfer.

Error in Chrome:
`xeoengine.js:33187 Uncaught TypeError: Cannot read property 'destroy' of null(…)`

On this line in `XEO.ColorTarget` object:
`this._state.renderBuf.destroy();`

Do I need to destroy some elements manually before calling `scene.destroy()`?

**Comment by xeolabs** [comment]
That sounds like a bug. BTW the version of BIMSurfer that uses SceneJS is not longer in development - we've replaced it with [this version](https://github.com/xeolabs/BIMsurfer), which I'd recommend using if possible.

**Comment by Bastien--** [comment]
I am using the latest version of BIMsurfer (V2) that uses xeogl.

**Comment by xeolabs** [comment]
Sorry, misread the message. On the face of it that sounds like a xeogl/xeoengine bug, but why are you calling ````scene.destroy()```` though? Since that's private within the [BIMSurfer viewer API](https://github.com/opensourceBIM/BIMsurfer/blob/master/bimsurfer/src/BimSurfer.js) (BIMSurfer.js fully encapsulates xeogl).

**Comment by xeolabs** [comment]
I checked xeogl, and that is a bug in xeogl though. I'll fix in a couple of days.

**Comment by Bastien--** [comment]
Thank you. I want to destroy an instance of BIMsurfer within my application. When I create another instance of BIMsurfer at a later stage the previous scene still exist since xeogl is a global/shared object. Not a big issue, it is just for optimisation purpose.

**Comment by xeolabs** [comment]
OK cool, I see. Since I recently renamed ````xeoEngine```` to ````xeogl````, I need to update that engine with BIMSurfer, which I'm planning to do next week. I'll include this fix as part of that.

In the meantime, if you need to, just wrap the call to ````this._state.renderBuf.destroy();```` with:

````javascript
if (this._state.renderBuf) {
      this._state.renderBuf.destroy();
}
````
And also do the same in the ````_destroy```` method of the xeoEngine ````DepthTarget```` component. Just search for all instances of  ````this._state.renderBuf.destroy();```` and ensure they are wrapped in that check. Those ````renderBuf```` vars are lazy-initialized, hence the check.

**Comment by bastienmenis** [comment]
I encountered another issue which may be related. When I load a model after another in BIMsurfer, it doesn't seem to destroy all the elements from the first model and it ends up showing some elements floating in the air at a random places. It does appear that some objects from the new model are loaded with the wrong geometry. Interestingly enough, if I click on one of these elements it highlights it at the correct location with the correct geometry.

Example:
![pic1](https://s12.postimg.org/t228yptjh/unselected.png)

When I click on one "floating" element (red arrow) it highlights it at the correct location:
![pic2](https://s12.postimg.org/6rizchln1/selected.png)

This is how the model looks like if I load it directly (i.e. first call of BIMsurfer.load()
![reference](https://s12.postimg.org/83w30mtot/reference.png)

Not sure if it is a problem with Bimsurfer or xeogl (or me!)

**Comment by xeolabs** [comment]
Probably a xeogl bug, since I see the BIMSurfer code path clears the model. I'll fix this one when I do the update to the latest xeogl build.
