### ISSUE TITLE
add support for touch input

### ISSUE THREAD

**Issue by emiyalee1005** [xeolabs/xeogl#139]
##### Description of the problem 

camera control is not working on mobile devices,which user input event is touch not mouse

##### xeogl version

- [ ] Dev
- [x] Master
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [x] IOS

**Comment by xeolabs** [comment]
@emiyalee1005 I'm working on this one at the moment

**Comment by dishesh** [comment]
@xeolabs Hey Please share any updates or improvements with this issue. Or please specify any third party libraries that we can implement to handle BimCameraControl. Thanks!

**Comment by xeolabs** [comment]
Hi, try xeogl.CameraControl and see if it works for you. If you have issues, or it's not the interaction you're looking for, then PRs are always welcome ;)

**Comment by xeolabs** [comment]
@dishesh @emiyalee1005 Hi, try xeogl.CameraControl and see if it works for you. If you have issues, or it's not the interaction you're looking for, then PRs are always welcome ;)

**Comment by dishesh** [comment]
@xeolabs No nothing works. I have following situation.
I want to rotate and handle ifc model that is rendered using BIMServer. I have all basic functions working with keyboard and mouse but i want touch support for model.

1. I tried simulating keyboard events on button click but it is not handled inside xeoGl / xeoviewer or bimcamera control as the are treated false events. 
2 I  converted basic touch events to map to mouse events and that is working well in Android but does not work in Apple iOS. 
3 third party libraries such as hammer js, for touch support is not working with my frameworks.

Can you please help me ?
Thanks.

**Comment by xeolabs** [comment]
@dishesh I can take a quick look to see if it's due to a xeogl bug - can you publish a live example somewhere?

**Comment by dishesh** [comment]
@xeolabs I will see what I can do for the live code. But I don't think that will help. But the main code that is accepting Scene's Input is in BimCameraControl and there is nothing that can be implemented for touchscreen input or 'tick' on the scene. I am using BimServer 1.5.69 to load ifc models, xeogl V1.0.0.

**Comment by xeolabs** [comment]
Ah I see now - BIMCameraControl just doesn't implement touch handlers. 

Don't worry about the live demo.

I'm afraid you'll need to implement those touch handlers yourself, if you need them. Note that all the JavaScript in ````examples/js```` are "experimental" and provided as boilerplates to get you started on your own extra components (much like the non-core components in the THREE.js examples).

Note that the core [xeogl.CameraControl](https://github.com/xeolabs/xeogl/blob/master/src/controls/cameraControl.js) component does have touch input handling control, however. Maybe you could use that as a guide to adding them to BIMCameraControl, unless CameraControl is everything you need.

**Comment by dishesh** [comment]
Okay, thanks for the info!
