### ISSUE TITLE
input div not move with canvas when running on single page webapp like angular

### ISSUE THREAD

**Issue by emiyalee1005** [xeolabs/xeogl#144]
##### Description of the problem 

...

##### xeogl version

- [ ] Dev
- [x] Master
- [ ] ...

##### Browser

- [] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
Hi, can you confirm that this example shows the problem for you: http://xeogl.org/examples/#canvas_movingInPage

Note the instructions at the top left of the example window, cheers

**Comment by emiyalee1005** [comment]
no,the example works fine.

**Comment by emiyalee1005** [comment]
i upload the ionic2 demo which will show you the problem
https://github.com/ionic2-ninja/emiya-angular2-bimsurfer

**Comment by emiyalee1005** [comment]
https://github.com/xeolabs/xeogl/pull/145
i fix this problem
