### ISSUE TITLE
Only a part of Buggy model of glTF-Embedded format is loaded.

### ISSUE THREAD

**Issue by cx20** [xeolabs/xeogl#165]
##### Description of the problem 

I tested xeogl + glTF Loader now.
It seems that glTF-Embedded format can not be read well.

glTF normal model
https://cx20.github.io/gltf-test/examples/xeogl/index.html?model=Buggy&scale=0.02&type=glTF
![image](https://cloud.githubusercontent.com/assets/1833979/21471487/5ec95bbc-caf8-11e6-9fc5-0077242c513c.png)

glTF-Embedded model
https://cx20.github.io/gltf-test/examples/xeogl/index.html?model=Buggy&scale=0.02&type=glTF-Embedded
![image](https://cloud.githubusercontent.com/assets/1833979/21471505/d7662816-caf8-11e6-9c4c-128238f149ce.png)

...

##### xeogl version

- [ ] Dev
- [x] Master
- [ ] ...

xeogl 2016.12.13

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements 

ThinkPad X260 + Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0

**Comment by xeolabs** [comment]
I actually forgot about ````dev```` branch and haven't even used it in a long time - it's 292 commits behind ````master````. Please ignore ````dev```` branch and just use ````master```` at the moment. 

My workflow has actually been ignoring ````dev````, sorry for confusion!

**Comment by cx20** [comment]
Sorry, I thought that I was using the `dev` branch, but it was a mistake.

I have tested using the version (2016.12.13) below.
https://github.com/xeolabs/xeogl/blob/master/build/xeogl.js

**Comment by cx20** [comment]
Since the presented URL has been changed, we will correct it below.

> glTF normal model

old) https://cx20.github.io/gltf-test/examples/xeogl/index.html?model=Buggy&scale=0.02&type=glTF
new) https://cx20.github.io/gltf-test/examples/xeogl/index.html?category=sampleModels&model=Buggy&scale=0.02&type=glTF

> glTF-Embedded model

old) https://cx20.github.io/gltf-test/examples/xeogl/index.html?model=Buggy&scale=0.02&type=glTF-Embedded
new) https://cx20.github.io/gltf-test/examples/xeogl/index.html?category=sampleModels&model=Buggy&scale=0.02&type=glTF-Embedded

If it can not be partially read, the following log is output to the console.

```

2xeogl.js:11122 [ERROR] [xeogl.Scene 'default.scene']: Component '5#prt_1_12_SOLIDS-mesh' already exists in Scene
    error @ xeogl.js:11122
    _addComponent @ xeogl.js:12113
    __init @ xeogl.js:10830
    Class @ xeogl.js:985
    value @ xeogl.js:29104
    value @ xeogl.js:28340
    loaderReady @ xeogl.js:28443
    JSONReady @ xeogl.js:28395
    jsonfile.onreadystatechange @ xeogl.js:28373
2xeogl.js:11122 [ERROR] [xeogl.Scene 'default.scene']: Component '5#prt_1_12_SOLIDS-mesh_1' already exists in Scene
    error @ xeogl.js:11122
    _addComponent @ xeogl.js:12113
    __init @ xeogl.js:10830
    Class @ xeogl.js:985
    value @ xeogl.js:29104
    value @ xeogl.js:28340
    loaderReady @ xeogl.js:28443
    JSONReady @ xeogl.js:28395
    jsonfile.onreadystatechange @ xeogl.js:28373
2xeogl.js:11122 [ERROR] [xeogl.Scene 'default.scene']: Component '5#prt_1_16_SOLIDS-mesh' already exists in Scene
    :
```
