### ISSUE TITLE
Reflect.getJSON fails when _src is null

### ISSUE THREAD

**Issue by bradwerth** [xeolabs/xeogl#169]
##### Description of the problem 
_getJSON calls this._src.slice() without first ensuring that this._src is non-null.

##### xeogl version

- [ ] Dev
- [X] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
I just removed the Reflect component, which fixes this problem - replaced with CubeTexture, which you can set as a light map or reflection map on xeogl.Lights components - see this example: http://xeogl.org/examples/#materials_metallic_metallicVsRoughness
