### ISSUE TITLE
GTFModel.getJSON checks undefined member property "src" instead of "_src"

### ISSUE THREAD

**Issue by bradwerth** [xeolabs/xeogl#170]
##### Description of the problem 
src/models/gltfModel.js line 156 (in _getJSON) tests "this.src" when it should test "test._src".

##### xeogl version

- [ ] Dev
- [X] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
I just rewrote ````GLTFModel```` to support glTF 2 - maybe this fixes things for you. Note that ````GLTFModel```` is now no longer part of the xeogl core, and must be loaded as a separate script, like in this example: https://github.com/xeolabs/xeogl/blob/master/examples/importing_gltf_2CylinderEngine.html

So maybe convert or re-export your model as v2.0, and if you still get problems we can reopen this ticket.
