### ISSUE TITLE
Is there a problem about xeogl.Clips?

### ISSUE THREAD

**Issue by theNann** [xeolabs/xeogl#171]
##### Description of the problem 
when i use xeogl.Clips, my program can not run correctly.I'm sure there's no problem with my program，is there a problem about xeogl.Clips? I didn't find example about Clips on http://xeogl.org/examples/.
...

##### xeogl version

- [ ] Dev
- [x] Master
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
Clips are not quite finished, not ready to use yet. I'll post a comment here when they're ready.

**Comment by xeolabs** [comment]
I've just finished support for user clipping planes -

Example: http://xeogl.org/examples/#clipping_userClipPlanes
API docs: http://xeogl.org/docs/classes/Clip.html
