### ISSUE TITLE
How to access to click in the model space coordinates of a point？？Thank you

### ISSUE THREAD

**Issue by hifeng97** [xeolabs/xeogl#177]
Thank you for your answer

**Comment by xeolabs** [comment]
Maybe the picking examples are useful:
https://github.com/xeolabs/xeogl/blob/master/examples/interaction_picking_triangles.html

API docs on picking:
http://xeogl.org/docs/classes/Scene.html#method_pick

**Comment by hifeng97** [comment]
@xeolabs Thank you，The model has been loaded, and how to add the model on this basis. I have Scene

**Comment by hifeng97** [comment]
Thank you. I found the solution
