### ISSUE TITLE
[Question] Object is cut off?

### ISSUE THREAD

**Issue by AlexanderChen1989** [xeolabs/xeogl#185]
##### Description of the problem 

...

##### xeogl version

- [ ] Dev
- [ ] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

##### Hardware Requirements 

![image](https://user-images.githubusercontent.com/2957936/28109538-f99400fa-6721-11e7-9bbf-75ab4d7b13c4.png)

**Comment by xeolabs** [comment]
Does the object disappear as its distance from the viewpoint increases? If so, then that would be the normal operation of the far clipping plane, which you can move farther back by adjusting the far clipping plane on the [http://xeogl.org/docs/classes/Perspective.html](perspective frustum).

**Comment by AlexanderChen1989** [comment]
@xeolabs thanks!
