### ISSUE TITLE
 multiple viewport at the same time show

### ISSUE THREAD

**Issue by yoyomule** [xeolabs/xeogl#186]
##### Description of the problem 
Hello, xeogl can support multiple viewport at the same time show? Similar to the threejs multi-viewport function(https://threejs.org/examples/webgl_multiple_views.html).
...

##### xeogl version

- [ ] Dev
- [ ] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
Hi, yes here you go: http://xeogl.org/docs/classes/Viewport.html
