### ISSUE TITLE
xeogl load prompts the error

### ISSUE THREAD

**Issue by yoyomule** [xeolabs/xeogl#189]
##### Description of the problem 
I through the FME tool to revit file into gltf, but now through the xeogl load prompts the error in the picture. In addition, I put the conversion of the documents also passed up for evaluation.
Thanks.

[fmetogltf.zip](https://github.com/xeolabs/xeogl/files/1179294/fmetogltf.zip)
![qq 20170727162514](https://user-images.githubusercontent.com/10000818/28661107-30e6a7fc-72e8-11e7-93f8-56006aa4b4cd.png)

**Comment by xeolabs** [comment]
I just rewrote ````GLTFModel``` to support glTF 2 - maybe this fixes things for you. Note that ````GLTFModel``` is now no longer part of the ceogl core, and must be loaded as a separate script, like in this example: https://github.com/xeolabs/xeogl/blob/master/examples/importing_gltf_2CylinderEngine.html

So maybe convert or re-export your model as v2.0, and if you still get problems we can reopen this ticket.
