### ISSUE TITLE
xeogl.DepthBuf where?  why?

### ISSUE THREAD

**Issue by shinseed** [xeolabs/xeogl#190]
![image](https://user-images.githubusercontent.com/13995240/29110960-167722d8-7d1b-11e7-8f1e-24be1b388062.png)
![image](https://user-images.githubusercontent.com/13995240/29110987-2da0de7c-7d1b-11e7-9ff4-e66b47cac45f.png)

**Comment by xeolabs** [comment]
Yes I removed nodes that manage certain WebGL state from the API, where that state will be controlled internally by xeogl for future effects like order-independent transparency etc. Allowing that state to be controlled through the API, in addition to xeogl controlling it internally, would make those future extensions too hard to implement. Sorry if this in causes confusion!
