### ISSUE TITLE
The model color problem

### ISSUE THREAD

**Issue by shinseed** [xeolabs/xeogl#193]
##### Description of the problem 

...
![image](https://user-images.githubusercontent.com/13995240/29392971-b7a6c546-8333-11e7-8526-a77dd38dc328.png)
canvas backgroundColor [0,0,0] 
obj mode color error 

##### xeogl version

- [ ] Dev
- [ x] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
Sorry, more information needed here.

**Comment by xeolabs** [comment]
I just rewrote ````GLTFModel```` to support glTF 2 - maybe this fixes things for you. Note that ````GLTFModel```` is now no longer part of the xeogl core, and must be loaded as a separate script, like in this example: https://github.com/xeolabs/xeogl/blob/master/examples/importing_gltf_2CylinderEngine.html

So maybe convert or re-export your model as v2.0, and if you still get problems we can reopen this ticket.
