### ISSUE TITLE
Rotating the model  will appear jitter

### ISSUE THREAD

**Issue by yoyomule** [xeolabs/xeogl#202]
##### Description of the problem 
The model, rotation, and movement of xeogl's canvas are achieved by rotating and moving the camera. We hope in the development activities, by rotating the model itself to achieve its rotation and movement, but found the model of rotation is realized by the rotation axis, it will appear model jitter, not clear what reason.

[test record.zip](https://github.com/xeolabs/xeogl/files/1331851/test.record.zip)
[test.zip](https://github.com/xeolabs/xeogl/files/1331852/test.zip)

**Comment by xeolabs** [comment]
The problem seemed to be in the modeling transform - try this, my changes are at lines 64 and 145:
[test.fixed.html.zip](https://github.com/xeolabs/xeogl/files/1331994/test.fixed.html.zip)

You could also use a quaternion, if you need a more free rotation: http://xeogl.org/docs/classes/Quaternion.html
