### ISSUE TITLE
Primitive broken in examples

### ISSUE THREAD

**Issue by mobiusVision** [xeolabs/xeogl#204]
##### Description of the problem 

Property Primitive :

xeogl.min.js:19 [ERROR] [xeogl.Entity '103B951D-F208-44E4-B61A-AB87920CBC9F']: Draw program failed to link

Varyings with the same name but different type, or statically used varyings in fragment shader are not declared in vertex shader: vViewNormal

Vertex shader:

##### xeogl version

- [ ] Dev
- [x] Master
- [x] latest version

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
Thanks - which example?

**Comment by mobiusVision** [comment]
@xeolabs Unfortunately, all examples related to 'primitives' are broken when changing primitives in the section Geometry. In fact, when I load an obj file, then set the primitives to have the wireframe mode, nothing shows up. T_T

**Comment by xeolabs** [comment]
To reduce complexity of xeogl, I've actually made the Geometry "primitive" property immutable, only able to be set within the Geometry constructor. Sorry if this causes problems!
