### ISSUE TITLE
About the model rotation center

### ISSUE THREAD

**Issue by AsaHiHXK** [xeolabs/xeogl#205]
Hi,
I encountered a problem when using xeogl development. You can not adjust the center of rotation when you rotate the model. When using the model vianney_house, rotate the center of the model at the edge of the model. How can i solve this problem.Thanks.
Best Regards
[test.zip](https://github.com/xeolabs/xeogl/files/1409244/test.zip)

**Comment by xeolabs** [comment]
Perhaps v0.8 has the solution for this, using the way that Models integrate with its new scene graph support: https://github.com/xeolabs/xeogl/wiki/Updates-in-xeogl-V0.8#new-features
