### ISSUE TITLE
.gltf loading is not working in IE 11

### ISSUE THREAD

**Issue by mkginfo** [xeolabs/xeogl#220]
##### Description of the problem 
.gltf loading is not working in IE 11
http://xeogl.org/examples/#picking_canvas_pickEntity
...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer IE 11

**Comment by xeolabs** [comment]
Any errors in the JS console?

**Comment by mkginfo** [comment]
Yes.
![error-load](https://user-images.githubusercontent.com/3713072/33068578-0df7b0ee-ceb2-11e7-80b0-73c523da09f7.PNG)

**Comment by mkginfo** [comment]
I am already find a solution. responseType set after calling open() method.
var request = new XMLHttpRequest();
      request.open('GET', ctx.basePath + url, true);
      request.responseType = 'arraybuffer';

**Comment by mkginfo** [comment]
Fixed for IE11.
