### ISSUE TITLE
Misprint: backface

### ISSUE THREAD

**Issue by D504** [xeolabs/xeogl#224]
https://github.com/xeolabs/xeogl/blob/2caeb1b37a3a16770498fea1eda746a2f1eb779e/src/materials/phongMaterial.js#L46

Probably it must be the "frontface" parameter.

**Comment by xeolabs** [comment]
Fixed: https://github.com/xeolabs/xeogl/commit/0dfd2995681f3d2b51088dfe38bf64484068ea99
