### ISSUE TITLE
how to get world point when i do a custom click

### ISSUE THREAD

**Issue by comger** [xeolabs/xeogl#226]
##### Description of the problem 
how to get world point when i do a custom click? like clientToWorld or screenToWorld; and how to project the world point by camera when camera change.

##### xeogl version

- [] Dev
- [x] Master
- [ ] ...

##### Browser

- [x] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
http://xeolabs.com/articles/xeogl-picking

**Comment by comger** [comment]
thanks, is so nice!
