### ISSUE TITLE
how to set model explode'scale?

### ISSUE THREAD

**Issue by comger** [xeolabs/xeogl#227]
##### Description of the problem 

hi bodys, do we have model explode method ? 

##### xeogl version

- [ ] Dev
- [ ] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
No, but it should be easy to make a non-core component that explodes other components. This example here might be helpful: http://xeogl.org/examples/#effects_demo_sportscar
