### ISSUE TITLE
Can we Drag select on every element in view area of model(xeoGL)?

### ISSUE THREAD

**Issue by Nisha93-tripathi** [xeolabs/xeogl#231]
##### Description of the problem 
I am beginner in xeogl and am trying to get a drag selection  on xeogl for selecting all elements but not getting it. please help me out.
...

##### xeogl version 1.0.0

- [yes ] Dev
- [yes ] Master
- [ ] ...

##### Browser

- [yes] All of them
- [x] Chrome
- [x] Firefox
-  Internet Explorer

##### OS

- [yes] All of them
- [x] Windows
- [x] Linux
- [x] Android
- [x] IOS

**Comment by xeolabs** [comment]
Sorry, marquee selection is not implemented, but do feel free to contribute it, if you do happen to implement it.

**Comment by Nisha93-tripathi** [comment]
yeah, am trying marquee.js and Three.js taking refrence of this(https://github.com/cubicleDowns/webgl-code-samples/blob/master/canvas-interaction/marquee-select.html) but in my case I am working on a model which is not in a cubic form.If you can help me to what to place in a parameter instead of (numcubes) in this line of code Demo.Scene = function (containerId, **numcubes**, marqueeBool, cacheBool)
