### ISSUE TITLE
Clicking on Link From Website Throws Errors

### ISSUE THREAD

**Issue by weshoke** [xeolabs/xeogl#236]
##### Description of the problem 

Clicking on this image/link:
<img width="599" alt="screen shot 2018-02-25 at 8 17 58 pm" src="https://user-images.githubusercontent.com/339696/36653306-1ebb0ea0-1a69-11e8-99a3-199bd99560d6.png">

Gives this error:
<img width="1433" alt="screen shot 2018-02-25 at 8 17 52 pm" src="https://user-images.githubusercontent.com/339696/36653307-1ecf3f60-1a69-11e8-999e-d65a4c45b063.png">
##### xeogl version

- [ ] Dev
- [ ] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
That was just how the examples gallery ungracefully handles a link to an example that no longer exists. Fixed website link.
