### ISSUE TITLE
Model remove

### ISSUE THREAD

**Issue by rubydesign** [xeolabs/xeogl#239]
##### Description of the problem 

The docs of Model talk about adding and removing, but there is no remove.
Whenever i touch _remove / removeAll / delete or destroy, i get WebGl warnings about buffers being used that don't belong to the program.

My guess is the rewrite was not quite finished in that area ? I couldn't see any examples either.
If you want i can knock a minimal failure together.

Currently i set visibility of all entities in the Model to false. which works :-)

##### xeogl version

- [ ] Dev
- [x ] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ x] macOs

**Comment by xeolabs** [comment]
True, I forgot to add ````remove()````! 

Fixed - https://github.com/xeolabs/xeogl/commit/287c09c112d4659def872933e768f3e6a41ddc51
