### ISSUE TITLE
Help with Saving and Loading a Scene?

### ISSUE THREAD

**Issue by ghost** [xeolabs/xeogl#25]
I'm using a build from December 23rd. I don't seem to be able to save and load a scene.

https://jsfiddle.net/philmaker/ueodzjjj

What am I doing wrong? I also tried this using the latest build but saw an error relating to _src.slice and " Cannot read property 'slice' of undefined"

**Comment by philmaker1** [comment]
This line looks suspicious to me:
https://github.com/xeolabs/xeoengine/blob/master/src/scene.js#L361

where:
constructor = window[type];

Should it be looking for the constructor in window.XEO?

**Comment by xeolabs** [comment]
Actually that line (eg for the XEO.Entity component) is resolving to window["XEO.Entity"], to get the constructor for that component from the global scope, so not a problem. 

Haven't got to this issue yet, will get on it this week or next. Note that serializing to/from JSON is not fully implemented yet.
