### ISSUE TITLE
OBJModel's meshes property hasn't any content.

### ISSUE THREAD

**Issue by horsefaced** [xeolabs/xeogl#268]
**Describe the bug**
When I use OBJModel.js to load a .obj file, the loaded model's meshes property hasn't any content.

**To Reproduce**
Look like this code：
```javascript
model.on("loaded", () => {
    for (let id in model.meshes) {
        console.info(id);
    }
});
```

**Repair Method**
I review the source code and discovered the 972 line in createMeshes function in OBJModel.js file。
```javascript
 
               var mesh = new xeogl.Mesh(model, {
                    id: model.id + "#" + object.id,
                    geometry: xeoGeometry,
                    material: material,
                    pickable: true
                });

                model.addChild(mesh);
```
The code just add mesh into model's children property, but not call Component._addComponent to add to compnents array, so the meshes property can't get anything. 
I modify this code to 
```javascript
               var mesh = new xeogl.Mesh(model, {
                    id: model.id + "#" + object.id,
                    geometry: xeoGeometry,
                    material: material,
                    pickable: true
                });

                model.addChild(mesh);
                model._addComponent(mesh);
```
Then the model.meshes can get meshes.

**Comment by xeolabs** [comment]
Thanks! Would you like to submit the fix via a pull request?
