### ISSUE TITLE
Convert to ES6

### ISSUE THREAD

**Issue by xeolabs** [xeolabs/xeogl#272]
Also use rollup, which will build xeogl as an ES6 module in ````build/xeogl.module.js````, and as a UMD module in ````build/xeogl.js````.

Doing the conversion in this branch: https://github.com/xeolabs/xeogl/tree/es6

- ~~Convert xeogl core to ES6~~
- ~~Configure rollup to build library as ES6 module and UMD module~~
- ~~Convert "extras" example components to ES6 classes~~
- ~~Use gulp instead of grunt~~

**Comment by MichaelDeBoey** [comment]
@xeolabs Are you planning on releasing this as an npm package too btw?
The unofficial one (https://www.npmjs.com/package/@wikifactory/xeogl) is still at `v0.7.2`, so it would be nice to have an official package published 🙂

**Comment by xeolabs** [comment]
@MichaelDeBoey yip will do!

**Comment by xeolabs** [comment]
The xeogl ES6 branch is now largely working if anyone needs to preview it. Will merge into master when I've updated the docs. Feedback is super welcome, please comment in this issue if you have any questions or feedback.

Change docs (WIP): https://github.com/xeolabs/xeogl/wiki/Updates-in-xeogl-v0.9
Repo branch: https://github.com/xeolabs/xeogl/tree/es6

**Comment by xeolabs** [comment]
I've just released v0.9, which converts xeogl to #ECMA6 -  https://github.com/xeolabs/xeogl/wiki/Updates-in-xeogl-v0.9

Next step: publish the core library as an npm package, along with some of the non-core components like GLTFModel. Just got some reading to do on all of that first.
