### ISSUE TITLE
Annotation's position is not correct

### ISSUE THREAD

**Issue by jacklincao** [xeolabs/xeogl#293]
When I use picked point dynamically as a Annotation, I find that canvasPos is sometimes incorrect. I try to solve it, but it fails. I don't know if other people have encountered such problems. I would appreciate it if I could give some help.

**Comment by xeolabs** [comment]
Could you provide a working example that shows the bug? Thanks

**Comment by jacklincao** [comment]
The operation video's link is [https://www.dropbox.com/s/dxc0p6jq6r3ubv8/EV~2018.12.06~17.1000.mp4?dl=0](url), and working example's link is [http://42.159.93.241:8080/#/design](url). Thanks.

**Comment by jacklincao** [comment]
This question is not a bug, I have fixed it. Thanks.
