### ISSUE TITLE
A CORS issue prevents the examples to be working locally with chromium web browser

### ISSUE THREAD

**Issue by amandinedrebes** [xeolabs/xeogl#301]
**Describe the bug**
A bug prevent to use the examples in chromium 

**To Reproduce**
1. checkout the project locally and switch on master branch (last commit was: ff87d12f6840fd745a27c36bc25d3eebefb72655)
2. open an example with chromium web browser. For example: importing_gltf_OfficePlan.html

Note: It works with firefox web browser.

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Browser: chromium

Chromium Screenshots (not working):
![chromium](https://user-images.githubusercontent.com/36631496/50582760-1ea31200-0e65-11e9-8865-14d36f866d80.png)
![chromium_version](https://user-images.githubusercontent.com/36631496/50582761-1f3ba880-0e65-11e9-8f99-ce8540fe32cf.png)

Firefox Screenshots (working):
![firefox](https://user-images.githubusercontent.com/36631496/50582763-1f3ba880-0e65-11e9-880d-b2bb90912a4f.png)
![firefox_version](https://user-images.githubusercontent.com/36631496/50582764-1f3ba880-0e65-11e9-94d9-dea676fe5820.png)

**Comment by xeolabs** [comment]
Thanks - I think loading the examples straight off the file system would be the problem here. 

Try serving them using [http-server](https://www.npmjs.com/package/http-server)
