### ISSUE TITLE
xeogl.org site broken

### ISSUE THREAD

**Issue by geohuz** [xeolabs/xeogl#307]
**xeogl.org is broken**

I can't open xeogl.org website.

**Comment by xeolabs** [comment]
Hi, works for me (from Germany) - what's the HTTP code you're getting? Could it be a firewall blocking your access?

**Comment by geohuz** [comment]
This site can’t be reached The connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET

**Comment by xeolabs** [comment]
Thanks - unable to reproduce, so guessing whatever caused this is resolved.
