### ISSUE TITLE
No error when .mtl library not found when loading .obj

### ISSUE THREAD

**Issue by arthur-parmentier** [xeolabs/xeogl#320]
**Describe the bug**
When loading .obj files without attached .mtl files (for instance that specifies only "usemtl"), no error is thrown whereas the file is not loading in the viewere

**To Reproduce**
Replace examples .obj files with any .obj file that specify "usemtl" instead of being associated with a .mtl file and test the examples.

**Expected behavior**
Error should be thrown such as "no mtl found)

**Comment by mhoelzner** [comment]
i provided a fix for that
https://github.com/xeolabs/xeogl/pull/324

**Comment by xeolabs** [comment]
Merged - thanks Arthur!
