### ISSUE TITLE
Explode tool for Models

### ISSUE THREAD

**Issue by xeolabs** [xeolabs/xeogl#81]
Would attach transforms to Model Entity's so they could be exploded away from each other.

**Comment by robbisy** [comment]
Lindsay is this tool still a project for xeogl or is it abandon ?

**Comment by xeolabs** [comment]
@robbisy I never got around to this, however if you want to implement it, the [car explosion demo](http://xeogl.org/examples/#effects_demo_sportscar) should give you a head start.
