### ISSUE TITLE
Wireframe mode

### ISSUE THREAD

**Issue by xeolabs** [xeolabs/xeogl#88]
Flexible antialiased wireframe rendering using barycentric coords:
http://codeflow.org/entries/2012/aug/02/easy-wireframe-display-with-barycentric-coordinates/

**Comment by mobiusVision** [comment]
Hello, would like you to add the wireframe mode to OBJGeometry?

**Comment by xeolabs** [comment]
You're welcome to add that and make a pull request if you like!

**Comment by xeolabs** [comment]
Check out the 'edges', 'highlighted', 'selected' and 'ghosted' effects - start with this one: http://xeogl.org/examples/#effects_ghost
